version: '3'
services:
  app_dev:
    build: .
    image: plebnet-website
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000

  app_build:
    build: .
    image: plebnet-website
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # environment:
      # - NODE_ENV=production
    command: npm run build